### ISSUE TITLE
Index of androgynous/nonbinary names

### ISSUE THREAD

**Issue by samanthashain** [SFDO-Community-Sprints/Snowfakery-Nonprofit#13]
## Feature Description

Many names are gendered in English and other languages.  Data generators may desire a list of names that are not obviously gendered and likely to be inferred as undetermined gender (Alex, Sam, Morgan, Jordan, Rowan, Corey, Rory).  This could be useful for consultants working with sample data who don't want to worry about pronouns, or for modeling data for organizations sensitive to LGBT communities.  Can we make a provider for this?

Feature suggested by @MelanieTolomeo !

Please describe the feature you are suggesting and why it would be useful.

## Proposed Solution

Propose a way to implement your feature to the degree you can. Requests for new generator functions should include a ideas for a pattern or data source whenever you can think of one.

https://www.adensmom.com/nonbinary-names/
https://kidadl.com/articles/non-binary-names-for-your-baby

**Comment by allisonletts** [comment]
https://data.world/ian/usa-baby-names-national-and-state-by-state/workspace/query?queryid=dcb3a50a-29f6-459a-8ba6-e9bc45f2a4b6 provides a possible approach to this problem. @prescod do you want to take this within Snowfakery or leave it as part of a community faker provider? If it's owned by the community, it should probably live in the diverse person names repo.

**Comment by allisonletts** [comment]
I wrote a replacement for that query, which basically looks at a 2/3 to 1/3 distribution as the max to be "gender neutral", and sorts by most popular names overall. Still uses the same dataset.

```sql
# these are names with similar numbers of male and female reports since 1980.
# 'Similar' is currently defined as at least 1/3 of reported babies were in the minority gender for the name.
    WITH counts AS (
    SELECT name,
               SUM(number) AS total,
               SUM(number) FILTER(WHERE sex = 'M') AS male,
               SUM(number) FILTER(WHERE sex = 'F') AS female
      FROM babynamesustotal
      WHERE yearofbirth > 1980
     GROUP BY name
)

SELECT name, total, male, female
  FROM counts
  WHERE total/3 < male and total/3 <female
 ORDER BY total desc
```

top names returned by this query, which seems right to me:

- Riley
- Casey
- Peyton
- Jaime
- Skyler
- Jessie
- Quinn
- Harley
- Justice
- Emerson
- Sidney
- Amari
- Rowan
- Sage
- Phoenix
- Kerry
- Elisha
- Finley
- Jackie
- Jean

**Comment by acrosman** [comment]
The basic feature for [nonbinary names actually exists now](https://snowfakery.readthedocs.io/en/latest/fakedata.html#fake-firstnamenonbinary).  It'll carry some of the same issues that triggered the need for the more [diverse person data generator](https://github.com/SFDO-Community-Sprints/faker_person_diverse) (that project is still just a stub today), and so I suggest changes to the baseline coming from Faker itself (which the existing function leverages) probably should get included there...and that project should become something useful not just a stub placeholder.

**Comment by allisonletts** [comment]
Unfortunately, faker nonbinary is more like faker I don't care about gender -- it just combines the male and female lists, at least in en_us.

**Comment by allisonletts** [comment]
@prescod @programmer2coder @mbeaty-sf

**Comment by allisonletts** [comment]
If we want to make this part of big faker, we need to make sure it's a subset of the existing data in faker.

**Comment by allisonletts** [comment]
Closed in favor of the issue above.
