### ISSUE TITLE
Function for generating names of foundations

### ISSUE THREAD

**Issue by nai888** [SFDO-Community-Sprints/Snowfakery-Nonprofit#15]
## Feature Description

There is currently a faker function for generating a list of nonprofit names. Some of these include "Foundation" and "Fund", but it would be useful to be able to generate a list of _only_ foundations/funds for fundraising use cases.

## Proposed Solution

Add another function `foundation_name` that combines company and person names with "Foundation", "Community Foundation", "Fund", etc.

**Comment by acrosman** [comment]
Thanks @nai888 that's a good suggestion. 

Do you think a human name should always be the suffix or a mix of those with other generated suffixes eg `Animal Support Fund` or and similar?

**Comment by nai888** [comment]
@acrosman I think it could be all of the above! A mix of “[Company] Foundation”, “[Name] Foundation”, “[Name] Community Foundation”, “[Cause] Fund”, etc., etc.

**Comment by acrosman** [comment]
I'm going to try to get a version of this done during the May OSC Sprint
